<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= $title ?></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
   
    <div class="container m-5">
        <?php if($template!=""): ?>
             <?php if(isset($_SESSION['id']) &&  ($_SESSION['IsEtudiant'])==1){?>
                <div class="dropdown ">
                    <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                        <img src="https://github.com/mdo.png" alt="mdo" width="32" height="32" class="rounded-circle">
                     </a>
                    <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
                        <li><a class="dropdown-item" href="#"><?=$_SESSION['nom']?></a></li>
                         <li><hr class="dropdown-divider"></li>
                     <li><a class="dropdown-item" href="../logout.php">Sign out</a></li>
                    </ul>
                </div>
                <?php }?>
                <?php if(isset($_SESSION['id']) &&  ($_SESSION['IsEtudiant'])==0) {?>
                    <p>Admin</p>
                     <a href="../logout.php">
                        <button class="btn btn-info">Logout</button>
                     </a>
                <?php } ?>
                 <?php include $template.".phtml"; ?>
        <?php else : ?>
            <div class="d-flex justify-content-center align-items-center mt-5 py-5">
             <a href="./Signup"> <button class="btn btn-primary mx-2">Signup</button></a>  
             <a href="./Login"> <button class="btn btn-info">Signin</button></a>
        </div>
        <?php endif; ?>
    </div>
   
</body>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
</html>