<div class="d-flex justify-content-center ">
     <form action="./index.php" method="POST" class="shadow p-5" >
        <h4>Signup</h4>
         <?php 
            if(array_key_exists("msg",$_GET)){
          ?>
            <div class="alert alert-danger">
                 <?= $_GET['msg']; ?>
            </div>
          <?php } ?>
         <div  class="mb-2">
             <input type="text" placeholder="Nom" name="nom" class="form-control" >
         </div>
         <div class="mb-2">
             <input type="text" placeholder="prenom"  name="prenom" class="form-control">
         </div>
         <div class="mb-2">
             <input type="text" placeholder="email"  name="email" class="form-control">
         </div>
         <div class="mb-2">
             <input type="text" placeholder="Password"  name="password" class="form-control">
         </div>
         
         <button type="submit" name="submit"  class="btn btn-outline-success">Signup</button>
     </form>
</div>